### ISSUE TITLE
Missing module mbapi

### ISSUE THREAD

**Issue by mostafa-najafiyazdi** [rozzac90/matchbook#1]
Dear Rozzac90,

I have been interested in the Matchbook API wrapper you are writing for matchbooks. I couldn't have it installed due to the following error:
`Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from matchbook import __version__
  File "C:\Users\Mostafa\Documents\matchbook\matchbook\__init__.py", line 2, in <module>
    from mbapi.exceptions import MBError
ModuleNotFoundError: No module named 'mbapi'`

Is it a python package provided to you by matchbook themselves?

**Comment by rozzac90** [comment]
Thanks for raising the issue, that is an old lib which shouldn't have been included at all I missed it in a renaming of the package.

I have uploaded new version to pypi so version 0.0.4 should pip install without these issues
